// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonBackendApp.Data;

#nullable disable

namespace MonBackendApp.Migrations
{
    [DbContext(typeof(badrDbContext))]
    partial class badrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentreIntéret", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_modification")
                        .HasColumnType("datetime2");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CentreIntérets");
                });

            modelBuilder.Entity("Certificat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_modification")
                        .HasColumnType("datetime2");

                    b.Property<int>("idPersonnes")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Certificats");
                });

            modelBuilder.Entity("Compétence", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_modification")
                        .HasColumnType("datetime2");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Compétences");
                });

            modelBuilder.Entity("Langue", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_modification")
                        .HasColumnType("datetime2");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Langues");
                });

            modelBuilder.Entity("MonBackendApp.Models.Experience", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_début")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_modification")
                        .HasColumnType("datetime2");

                    b.Property<string>("entreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPersonnes")
                        .HasColumnType("int");

                    b.Property<string>("remarque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("MonBackendApp.Models.Formation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("actuel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_début")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_modification")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ecole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPersonnes")
                        .HasColumnType("int");

                    b.Property<string>("titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("MonBackendApp.Models.Personne", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("code_postal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_modification")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lien_facebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lien_instagram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lien_linkdin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lien_twitter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mot_de_passe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nombre_d_experience")
                        .HasColumnType("int");

                    b.Property<string>("permis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titre_poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("MonBackendApp.Models.PerssLang", b =>
                {
                    b.Property<int>("idPersonnes")
                        .HasColumnType("int");

                    b.Property<int>("idLangues")
                        .HasColumnType("int");

                    b.Property<int>("niveau")
                        .HasColumnType("int");

                    b.HasKey("idPersonnes", "idLangues");

                    b.HasIndex("idLangues");

                    b.ToTable("PerssLangs");
                });

            modelBuilder.Entity("Projet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Remarque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_modification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_projet")
                        .HasColumnType("datetime2");

                    b.Property<int>("idPersonnes")
                        .HasColumnType("int");

                    b.Property<string>("lien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("MonBackendApp.Models.PerssLang", b =>
                {
                    b.HasOne("Langue", "langue")
                        .WithMany("PerssLang")
                        .HasForeignKey("idLangues")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonBackendApp.Models.Personne", "personne")
                        .WithMany("PerssLang")
                        .HasForeignKey("idPersonnes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("langue");

                    b.Navigation("personne");
                });

            modelBuilder.Entity("Langue", b =>
                {
                    b.Navigation("PerssLang");
                });

            modelBuilder.Entity("MonBackendApp.Models.Personne", b =>
                {
                    b.Navigation("PerssLang");
                });
#pragma warning restore 612, 618
        }
    }
}
